name: Release
on:
  workflow_dispatch:
    inputs:
      newversion:
        description: "Version bump"
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry-url: "https://registry.npmjs.org"
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: git config --global user.email "v.klepov@gmail.com"
      - run: git config --global user.name "thoughtspile"
      - run: npm version ${{ inputs.newversion }}
      - run: git push --follow-tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
